Improvement/homogenize profile styles
EquestriaReapers/ER-frontend pull request #16
Opened 2023-12-24 02:28 UTC by luizzzito

🧪 Testing!
Puedes probar en staging en el link: https://ucab-profile-staging.playoffside.online/profile/1.

Puedes autenticarte con las credenciales:

[davidsalcedo388@gmail.com](mailto:davidsalcedo388@gmail.com)
123456

2023-12-26 23:07 UTC, Yisustxz approved these changes
una vaina bien 😎

2023-12-29 02:55 UTC, Hector1567XD requested changes
Atrosidak

2023-12-29 02:55 UTC, Hector1567XD commented on src/hooks/use-transform-career-enum.ts
> +export default useTransformCareerEnum;
```suggestion
const careerEnum: Record<string, string> = {
  "ingenieria-industrial": "Ingeniería Industrial",
  "ingenieria-informatica": "Ingeniería Informática",
  "ingenieria-civil": "Ingeniería Civil",
  "ingenieria-telecomunicaciones": "Ingeniería en Telecomunicaciones",
  "arquitectura": "Arquitectura",
  "derecho": "Derecho",
  "psicologia": "Psicología",
  "filosofia": "Filosofía",
  "teologia": "Teología",
  "letras": "Letras",
  "educacion": "Educación",
  "comunicacion-social": "Comunicación Social",
  "administracion": "Administración",
  "contaduria": "Contaduría",
  "relaciones-industriales": "Relaciones Industriales",
  "sociologia": "Sociología",
  "economia": "Economía",
};

const useTransformCareerEnum = (careerName: string) => careerEnum[careerName] || null;
```

2023-12-29 22:27 UTC, luizzzito commented on src/hooks/use-transform-career-enum.ts
> +export default useTransformCareerEnum;
recordzzz, if le gana

2023-12-29 22:47 UTC, merged