Feature/download vc pdf
EquestriaReapers/ER-frontend pull request #18
Opened 2023-12-26 20:28 UTC by luizzzito

🧪 Testing!
Puedes probar en staging en el link: https://ucab-profile-staging.playoffside.online/profile/1.

Puedes autenticarte con las credenciales:

[davidsalcedo388@gmail.com](mailto:davidsalcedo388@gmail.com)
123456

2023-12-27 02:12 UTC, Yisustxz approved these changes
todo piola

2023-12-29 02:50 UTC, Hector1567XD requested changes
No me pude dar el lujo de hacer buen code-review, tenemos que pasarlo rapido... no con gran calidad (de momento)

2023-12-29 02:50 UTC, Hector1567XD commented on src/features/profile/profile-content/use-download-curriculum-pdf.tsx
> +      const response = await exportCurriculumPDF(token, profile.userId);
```suggestion
      const response = await exportCurriculumPDF(profile.userId);
```

2023-12-29 02:50 UTC, Hector1567XD commented on src/features/profile/profile-content/use-download-curriculum-pdf.tsx
> +      const response = await exportCurriculumPDF(token, profile.userId);
No deberia requererir el token

2023-12-29 02:50 UTC, Hector1567XD commented on src/features/profile/profile-content/use-download-curriculum-pdf.tsx
> +  return { downloadCurriculumPDF };
```suggestion
  return downloadCurriculumPDF;
```

2023-12-29 22:26 UTC, merged