Feature/homepage
EquestriaReapers/ER-frontend pull request #21
Opened 2023-12-30 15:24 UTC by Jesus-D-Rodriguez

La homepage esta en /home

2023-12-31 03:25 UTC, luizzzito requested changes
Papa, en resumen, separa la homepage en componentes, los archivos tienen muchas lineas de codigo, asi que debes crear otros componentes como hemos hecho en los otros features. Igual debes hacer lo mismo con los estilos. los estilos que uses en los componentes que vas a crear, los colocas en archivos distintos.

2024-01-03 15:24 UTC, Yisustxz approved these changes

2024-01-04 14:49 UTC, Hector1567XD commented
@Yisustxz esto tiene un cambio que rompe la aplicacion, no le deberias haber dado approve. vuelve a revisar

2024-01-04 22:49 UTC, Yisustxz approved these changes
todo piola

2024-01-04 22:58 UTC, luizzzito reviewed
Ademas de los cambios que mencione antes, recuerda que esta sera la landing page, por lo que debes cambiar todas las rutas (en vez de ser "/home", ahora es "/") y lo otro es que todas las carpetas y componentes que digan "Home" deberian decir "Landing".

2024-01-04 23:06 UTC, Nannajpg approved these changes

2024-01-04 23:06 UTC, Nannajpg commented on src/features/auth/styles/ForgotPaswordStyles.tsx
> +import background from "../images/background.jpeg"
Los tamaños de las fuentes creo que deberían ser más consistentes con los que hay en el resto de lugares (como en perfil que están en px)

2024-01-04 23:06 UTC, Nannajpg commented on src/features/auth/styles/NewPasswordStyles.tsx
> +import background from "../images/background.jpeg";
Lo mismo, sólo fuentes

2024-01-07 17:09 UTC, Hector1567XD approved these changes
Hay demaciadas cosas que mejorar, pero por mi, esta bien, por que podemos arreglarlo luego en la tarea dedicada a la landing

Igual, haz los fixes de @luizzzito y @Nannajpg para mergearlo.

2024-01-07 18:46 UTC, luizzzito approved these changes
Los comentarios que hice fueron aplicados correctamente, buen trabajo ❤️❤️

2024-01-07 18:48 UTC, merged