Feature/modal contact
EquestriaReapers/ER-frontend pull request #26
Opened 2023-12-31 18:04 UTC by GreenieWarren

Este es mi primer pull request. No mas aprendiendo acá lets goooo

2024-01-04 23:37 UTC, luizzzito approved these changes
Arregle cositas con relaciones a los estilos del boton, elimine comentarios innecesarios, y corregi errores ortograficos con respecto a nombres de variables.

2024-01-06 18:01 UTC, Hector1567XD commented
Solo faltan cosas de responsive que se encargaran @GreenieWarren y @Nannajpg

2024-01-07 15:28 UTC, Hector1567XD commented
rEsponsive no es repsonsive
![image](https://github.com/EquestriaReapers/ER-frontend/assets/22270579/a309e6ab-fc14-4b5d-99dd-18e46e14642c)

2024-01-07 15:28 UTC, Hector1567XD requested changes
maxHeight y un scroll

2024-01-07 17:05 UTC, Hector1567XD approved these changes
Ese fix que comente lo deje en https://github.com/EquestriaReapers/ER-frontend/pull/37

2024-01-07 17:05 UTC, merged

2024-01-07 18:41 UTC, Nannajpg approved these changes
Fino