Feature/forgot password: Olvido contraseña y nueva contraseña
EquestriaReapers/ER-frontend pull request #28
Opened 2024-01-02 01:13 UTC by Jesus-D-Rodriguez

Los links estan en /forgot-password y /new-password

2024-01-03 15:42 UTC, Yisustxz approved these changes

2024-01-04 23:11 UTC, luizzzito approved these changes
Agregue bordes a las cards, que se ajusta mas a los estilos actuales

2024-01-05 00:43 UTC, Nannajpg approved these changes

2024-01-05 00:43 UTC, Nannajpg commented on src/features/auth/styles/NewPasswordStyles.tsx
> +import background from "../images/background.jpeg";
Los tamaños de letra creo que deberían ser como los de los demás lugares (en px por ejemplo)

2024-01-05 00:43 UTC, Nannajpg commented on src/features/auth/styles/ForgotPaswordStyles.tsx
> +import background from "../images/background.jpeg";
Los tamaños de fuente :T

2024-01-05 14:21 UTC, Hector1567XD requested changes
Haz los fixes de Anna

2024-01-08 01:01 UTC, Hector1567XD approved these changes

2024-01-08 03:31 UTC, Yisustxz approved these changes

2024-01-08 05:15 UTC, merged