Improvement/use token in middleware
EquestriaReapers/ER-frontend pull request #3
Opened 2023-11-17 17:35 UTC by Nannajpg

🤔 Problem
Agregar token en middleware

✅ Solution
token en middleware

2023-11-17 18:03 UTC, Hector1567XD commented
@luizzzito @Nannajpg pueden compartir instrucciones de como probar? (si es que hace falta probar)

2023-11-17 18:05 UTC, Hector1567XD requested changes

2023-11-17 18:05 UTC, Hector1567XD commented on src/app/config.ts
> +export const BACKEND_V2_URL = "https://ucab-profile-backend.playoffside.online/api/v1";
AMBAS son APIv1
```suggestion
export const BACKEND_V1_URL = "https://ucab-profile-backend.playoffside.online/api/v1";
```
Si emmanuel hiciera un nuevo versionamiento como `https://ucab-profile-backend.playoffside.online/api/v2` entonces si te creeria que amerita un `API_V2` pero este no es el caso.]

Lejos de eso... esto deberia evolucionar a algo asi:
```suggestion
export const BACKEND_V1_URL = process.env.REACT_APP_BLABLABLA_BACKEND_V1_URL;
```
Pero supongo aun no se hace el tema del .env

2023-11-17 18:32 UTC, Hector1567XD commented on src/hooks/use-redirect-when-unlogged.ts
> +    }
Maybe
```suggestion
    if (!isLogged) navigate(`/login`);
```
Optional, just a preference

2023-11-17 18:32 UTC, Hector1567XD commented on src/hooks/use-redirect-when-logged.ts
> +      return;
**En este caso**, el return es innecesario
```suggestion
```

2023-11-17 18:32 UTC, Hector1567XD commented on src/hooks/use-redirect-when-logged.ts
> +  }, [navigate, isLogged, user]);
Solo dependes del `user.id` no del objeto `user` completo, muchas veces si hay que pasarlo completo o hacer las distinciones es poco practicó, pero este no es el caso
```suggestion
  }, [navigate, isLogged, user.id]);
```

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/profile/use-profile-state.ts
> +}
Tenemos 2 opciones:

1. Definir o encontrar un tipado para el estado "en blanco" del perfil (no es realmente necesario, pero opino yo que ayuda mucho a propagar un tipado correcto).

```suggestion
import { Profile } from '......';
type NulledProfile = Partial<Profile>; /* Partial hace que todas las propiedades del perfil sean opcionales, puedes hacerlo de otra forma tambien */

export const DEFAULT_PROFILE_STATE: NulledProfile = {
    userId: null as number | null,
    image: "",
    description: "",

    user: {
      email: "",
      id: 0,
      name: "",
      role: "",
      deletedAt: null as Date | null,
    },
  }

export default function useProfileState() {
  const [profile, setProfile] = useState<Profile | NulledProfile>(DEFAULT_PROFILE_STATE);
  return { profile, setProfile };
}
```

2. Mi favorita, usar un null state xd (esto te hará posiblemente tener errores en el frontend por que deberas validar ANTES que profile no sea `null` pero me parece que es correcto que ocurran ésos errores para corregir eso a conciencia)

```suggestion
import { Profile } from '......';

export default function useProfileState() {
  const [profile, setProfile] = useState<Profile | null>(null);
  return { profile, setProfile };
}
```

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/profile/use-profile-state.ts
> +}
Pensandolo, si vamos por la opcion 2, quiza nisiquiera tenemos que encapsular xd (almenos por ahora)

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +  }, [getProfile]);
el `useCallback getProfile` y el `useEffect` que lo activa, perfectamente pueden estar dentro de `useProfileState()`; eso reduciria el codigo aqui, haria que `useProfileState` tuviera mas cohesion y ademas haria que evitemos exponer `setProfile` ya que, ¿para que lo queremos sacar?, haria que fuese un estado de "read-only" para lo que respecta al componente

```suggestion
  const profile = useProfileState();

  const id = parseInt(useParams<RouteParams>().id!);

  function useAuthState(): AuthState {
    return useSelector<{ auth: AuthState }>((state) => state.auth) as AuthState;
  }
  const { token } = useAuthState();
  const loggedUser = useAuthState().user;
```

Aun asi, tambien podemos exponer quiza "getProfile" junto a "profile" por si lo queremos usar para re-cargar los datos del perfil (lo cual es bastante comun)

Si hacemos esto, lo que comente en mi comentario anterior de que ya no es necesario encapsular si vamos por la opcion numero 2, seria falso, ahora si hay razon para encapsular

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +  const loggedUser = useAuthState().user;
```suggestion
  const { token, user } = useAuthState();
```
O... si quieres usar el alias
```suggestion
  const { token, user: loggedUser } = useAuthState();
```

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +  }
No hay razon para hacer esto a nivel de componente 😨

Puedes definir esta funcion hasta ABAJO de profile, tipo en la linea 93 luego de la interface

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +  const id = parseInt(useParams<RouteParams>().id!);
¿Que pasa si no es un numero?, ¿que pasa si meten texto?, ¿que pasa si es un defined?

Quiza todo eso lo puedas contemplar con mejor detalle y dando mensajes de error si haces algo como
```suggestion
  const id = useParamId();
```
O algo quiza mas concreto...
```suggestion
  const id: number | null = useParamId();
  if (!id) return <ErrorComponent />; /* no estoy seguro de que esto se pueda hacer en esta parte del codigo, quiza debe ser ANTES del otro render por temas de hooks condicionales */
```

Algo mas concreto y quiza mas seguro seria:
```suggestion
  const id: number | null = useParamId();
  useEffect(() => {
     if (!id) redirect('/..../error');
  }, [id]);
```

Ahora, yo realmente pondria eso DENTRO de useParamId(); asi que volvemos al original xd
```suggestion
  const id = useParamId();
```

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +      }
Evitemos niveles de abstraccion innecesarios, investiga sobre `Guard Clausures`, imagen que lo resume:

![image](https://github.com/luizzzito/ER-frontend/assets/22270579/8be4817c-f632-46bd-a463-2b94da14d69d)

```suggestion
      if (!token || !id) return;

      const data = await fetchOneProfile(token, id);
      setProfile(data);
      console.log(token);
```

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +      }
Si preguntas por que cambie de `if (A && B)` hacia `if (!A || !B)` es por la **Ley de De Morgan** 
```
¬(A∧B)=(¬A)∨(¬B)
```
Hijo.

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +        console.log(token);
Deberiamos evitar que lleguen console.log a produccion
```suggestion
```

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +      console.log(error);
Deberiamos evitar que lleguen console.log a produccion
```suggestion
      console.log(error);
```
Aunque en este caso como es un error podria convenir... pero idk
```suggestion
      console.error(error);
```
Pero muchisisimo mas importante, donde esta la recuperacion o la notificacion al usuario de que hubo un error 🧐??
```suggestion
      mostrarNotificacionDeError(error);
```
toastify??

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/auth/Login.tsx
> +import useRedirectWhenLogged from "../../hooks/use-redirect-when-logged";
Si es una importación de tan atrás, hazlo una importación absoluta
```suggestion
import useRedirectWhenLogged from "hooks/use-redirect-when-logged";
```

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/auth/services/login.service.ts
> +const URL = `${BACKEND_V2_URL}/auth/login`;
Es uno de mis primeros comentarios
```suggestion
const URL = `${BACKEND_V1_URL}/auth/login`;
```

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/auth/store/index.ts
> +      localStorage.removeItem('auth');
Dijiste que lo solucionaste con redux-persist, entonces que hace esto aqui 🤔?

(Me refiero a `localStorage.setItem('auth', JSON.stringify(state));` y `localStorage.removeItem('auth');`).

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/dashboard/Dashboard.tsx
> +  }
Just a preference
```suggestion
  if (!user) return null;
```

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/dashboard/Dashboard.tsx
> +function useCurrentUser(): User {
```suggestion
function useCurrentUser(): User | null {
```

2023-11-17 18:32 UTC, Hector1567XD commented on src/features/dashboard/Dashboard.tsx
> +function useCurrentUser(): User {
Si no pones el tipado correcto la gente podria esperar recibir algo que al final no vendra

2023-11-17 19:06 UTC, Hector1567XD reviewed
Ahora si, ya con estos otros comentarios, finalizo mi Review ✅.

2023-11-17 19:06 UTC, Hector1567XD commented on src/features/profile/services/profile.service.ts
> +    const response = await axios.get(URL + "/" + profile_id, {
Es mas facil manejarlo asi
```suggestion
    const response = await axios.get(`${URL}/${profile_id}`, {
```

2023-11-17 19:06 UTC, Hector1567XD commented on src/features/profile/services/profile.service.ts
> +  profile_id: number
snake_case??? 🐍
```suggestion
  profileId: number
```

2023-11-17 19:06 UTC, Hector1567XD commented on src/features/profile/services/profile.service.ts
> +import { BACKEND_V2_URL } from "app/config";
Considero que cada servicio es lo suficientemente grande como para que hagas 2 archivos diferentes para los 2 servicios

Mas pensando en cuando no sean 2 si no que sean 4 o 5

2023-11-17 19:06 UTC, Hector1567XD commented on src/features/profile/services/profile.service.ts
> +) {
Mas de 3 argumentos en una funcion 😨? 

El tio Bob sataniza eso, recomienda usar un objeto a partir de 2 parametros
```suggestion
export async function updateProfile({
  token,
  body,
  profileId
}: {
  token: string,
  body: updateProfileBody,
  profileId: number
}) {
```

2023-11-17 19:06 UTC, Hector1567XD commented on src/features/profile/services/profile.service.ts
> +export interface updateProfileBody {
CapitalCase creo se llama o PascalCase
```suggestion
export interface UpdateProfileBody {
```
![image](https://github.com/luizzzito/ER-frontend/assets/22270579/8b83689e-0a88-4e5b-8db7-ee4adcb01431)

2023-11-17 19:06 UTC, Hector1567XD commented on src/features/profile/components/show-skills.tsx
> +        </Typography>
Encapsular todo el componente hijo
```suggestion
        <SkillComponent key={item.id} skill={item} />
```

2023-11-17 19:06 UTC, Hector1567XD commented on src/features/profile/components/show-experiences.tsx
> +
```suggestion
            <Typography
              variant="h5"
              sx={{ background: "white", fontWeight: "bold" }}
            >
              {item.projectName}
            </Typography>
            <ExperiencieTextProperty>
              {item.url}
            </ExperiencieTextProperty>
            <ExperiencieTextProperty>
              {item.position}
            </ExperiencieTextProperty>
            <ExperiencieTextProperty>
              {item.entityName}
            </ExperiencieTextProperty>
            <ExperiencieTextProperty>
              {item.description}
            </ExperiencieTextProperty>
          </Box>
        );
      })}
    </Box>
  );
};

// Para no crear un nuevo componente en un nuevo archivo, podria ser un mini componente aqui mismo
function ExperiencieTextProperty: FunctionComponent<{ children?: React.ReactNode; }> = ({ children }) => {
return  (<Typography variant="h6" sx={{ background: "white" }}>
              {children}
            </Typography>)
}
// Aunque ahora que lo pienso, perfectamente podria ser un componente aparte en una carpeta /show-experiencies/...
```

Otra opcion quiza mejor xd

```suggestion
            <Typography
              variant="h5"
              sx={{ background: "white", fontWeight: "bold" }}
            >
              {item.projectName}
            </Typography>
            <ExperiencieTextProperty title={item.url} />
            <ExperiencieTextProperty title={item.position} />
            <ExperiencieTextProperty title={item.entityName} />
            <ExperiencieTextProperty title={item.description} />
          </Box>
        );
      })}
    </Box>
  );
};

function ExperiencieTextProperty: FunctionComponent<{ title: string; }> = ({ title }) => {
return  (<Typography variant="h6" sx={{ background: "white" }}>
              {title}
            </Typography>)
}
```

2023-11-17 19:06 UTC, Hector1567XD commented on src/core/profiles/types.ts
> +  };
Maybe?
```suggestion
  user: User;
```

2023-11-17 19:06 UTC, Hector1567XD commented on src/core/profiles/types.ts
> +}
De cierta forma pienso que esto deberia tener su propia entidad pero a la vez no... podemos dejarlos aqui mientras ✅

2023-11-17 19:06 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +      {loggedUser && loggedUser.id == id && (
```suggestion
  const isMyProfile = loggedUser && loggedUser.id == id;
  return (
    <Box sx={{ margin: "10px" }}>
      <Typography variant="h3">Perfil:</Typography>
      {isMyProfile && (
        <Link to={`/profile/edit/${profile.user.id}`}>
          <IconButton>
            <EditIcon />
          </IconButton>
        </Link>
      )}

      <Typography variant="h4">Nombre:</Typography>
      <Typography variant="h6">{profile.user.name}</Typography>
      <Box
        component="img"
        sx={{ height: 100, width: 100, maxHeight: 100, maxWidth: 100 }}
        src={profile.image}
        alt={profile.user.name}
      />

      <Typography variant="h4">Email:</Typography>
      <Typography variant="h6">{profile.user.email}</Typography>

      <Typography variant="h6">{profile.description}</Typography>

      <Typography variant="h4">Habilidades:</Typography>
      {isMyProfile && (
        <Link to={`/profile/edit/${profile.user.id}`}>
          <IconButton>
            <EditIcon />
          </IconButton>
        </Link>
      )}
      <ShowSkills />

      <Typography variant="h4">Experiencia:</Typography>
      {isMyProfile && (
```

Tambien puedes encapsular esa pequeña comprobacion en un custom-hook si es que quieres
```
const isMyProfile = useIsMyProfile();
```

2023-11-17 19:06 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +      <Link to="/dashboard"> Regresar </Link>
Encapsular
```suggestion
      <ProfileExperiencies profile={profile} isMyProfile={isMyProfile} />
      <Link to="/dashboard"> Regresar </Link>
```

2023-11-17 19:06 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +      <ShowSkills />
Encapsular
```suggestion
      <ProfileSkills profile={profile} isMyProfile={isMyProfile} />
```

2023-11-17 19:06 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +      <Typography variant="h6">{profile.description}</Typography>
Estos nombres que te estoy proponiendo son Xd... no se si sean correctos usa tu criterio para mejorarlos o dejarlos igual, lo importante es **ENCAPSULAR**.
```suggestion
      <ProfileMainData profile={profile} isMyProfile={isMyProfile} >
```

2023-11-17 19:27 UTC, luizzzito commented on src/app/config.ts
> +export const BACKEND_V2_URL = "https://ucab-profile-backend.playoffside.online/api/v1";
Listo los cambios a todas las URL de los servicios

2023-11-17 19:30 UTC, luizzzito commented on src/core/profiles/types.ts
> +}
ok. listo.

2023-11-17 19:31 UTC, luizzzito commented on src/features/auth/Login.tsx
> +import useRedirectWhenLogged from "../../hooks/use-redirect-when-logged";
Chevere, lo que pasa es que eso fue antes de que agregaramos el tema de la importacion absoluta xD

2023-11-17 19:31 UTC, luizzzito commented on src/features/auth/services/login.service.ts
> +const URL = `${BACKEND_V2_URL}/auth/login`;
Listo

2023-11-17 19:31 UTC, luizzzito commented on src/features/auth/store/index.ts
> +      localStorage.removeItem('auth');
yeah, se me olvido quitarlo xD, my bad.

2023-11-17 19:33 UTC, luizzzito commented on src/features/dashboard/Dashboard.tsx
> +  }
esta bien, son lineas de codigo menos.

2023-11-17 19:34 UTC, luizzzito commented on src/features/dashboard/Dashboard.tsx
> +function useCurrentUser(): User {
chevere

2023-11-17 19:36 UTC, luizzzito commented on src/features/profile/Profile.tsx
> +  const id = parseInt(useParams<RouteParams>().id!);
pero wait, useParamId vendria a ser un componente extra? una funcion extra?

2023-11-17 19:37 UTC, luizzzito commented on src/features/profile/Profile.tsx
> +  }
Yo diria que si la hay, al final es algo que utilizas en un monton de pantallas en toda la aplicacion, y son menos lineas de codigo y es mas practico. Asi lo vi yo.

2023-11-17 19:38 UTC, luizzzito commented on src/features/profile/Profile.tsx
> +  const loggedUser = useAuthState().user;
curioso, no sabia que se podia hacer eso, gracias xD

2023-11-17 19:38 UTC, luizzzito commented on src/features/profile/Profile.tsx
> +        console.log(token);
Uy si, por supuesto

2023-11-17 19:41 UTC, luizzzito commented on src/features/profile/Profile.tsx
> +      }
oka

2023-11-17 19:49 UTC, luizzzito commented on src/features/profile/Profile.tsx
> +      console.log(error);
enfocaria eso para el siguiente sprint, son detalles que todavia no he podido investigar, y no son prioridad por ahora

2023-11-17 19:51 UTC, luizzzito commented on src/features/profile/Profile.tsx
> +  }, [getProfile]);
creo que queda mas bonito colocandolo en otro componente, tambien lo pense pero no sabia que tan bueno era hacerlo XD

2023-11-17 20:00 UTC, luizzzito commented on src/features/profile/components/show-experiences.tsx
> +
Lo que no entiendo, es para que hacer eso? que tiene de malo usar el Typography? lo que si creo que deberiamos quitar el sx, porque no tiene estilos todavia

2023-11-17 20:01 UTC, luizzzito commented on src/features/profile/components/show-skills.tsx
> +        </Typography>
Si, lo que pasa es que diria que eso va un poco de la mano con los estilos (?) por eso no lo hice asi, pero si esta contemplado

2023-11-17 20:02 UTC, luizzzito commented on src/features/profile/services/profile.service.ts
> +  profile_id: number
odio las culebras

2023-11-17 20:02 UTC, luizzzito commented on src/features/profile/services/profile.service.ts
> +    const response = await axios.get(URL + "/" + profile_id, {
true

2023-11-17 20:03 UTC, luizzzito commented on src/features/profile/services/profile.service.ts
> +) {
para ese momento el update no estaba listo, por lo que eso lo tomare en cuenta para el PR que subire despues

2023-11-17 20:03 UTC, luizzzito commented on src/features/profile/services/profile.service.ts
> +) {
en esta branch no solucione el update de perfil, solo el mostrar.

2023-11-17 20:04 UTC, luizzzito commented on src/features/profile/services/profile.service.ts
> +export interface updateProfileBody {
Pascal

2023-11-17 20:05 UTC, luizzzito commented on src/features/profile/use-profile-state.ts
> +}
creo que la opcion correcta es la 2, pero si creo que es algo que me gustaria resolver en la otra rama, porque ahi es donde tengo todo actualizado.

2023-11-17 20:06 UTC, luizzzito commented on src/hooks/use-redirect-when-logged.ts
> +      return;
listo

2023-11-17 20:08 UTC, luizzzito commented on src/hooks/use-redirect-when-logged.ts
> +  }, [navigate, isLogged, user]);
listo, pero me da un error diciendo que el user puede ser null, por lo que le coloque user?.id

2023-11-17 20:09 UTC, luizzzito commented on src/hooks/use-redirect-when-unlogged.ts
> +    }
a mi tb me gusta mas asi

2023-11-17 20:13 UTC, luizzzito commented on src/features/profile/components/show-skills.tsx
> +        </Typography>
lo dejamos asi por ahora? y el siguiente sprint cuando tome en cuenta los estilos lo cambio? o lo cambio de una vez?

2023-11-17 20:44 UTC, luizzzito commented on src/features/profile/services/profile.service.ts
> +import { BACKEND_V2_URL } from "app/config";
ok?

2023-11-22 12:12 UTC, Hector1567XD commented on src/features/profile/use-profile-state.ts
> +}
Copiado!

2023-11-22 12:15 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +  }, [getProfile]);
Hmm puede ir en otro componente tambien

Pero ese seria un componente padre que tendria dentro de si ese custom-hook del que te estoy hablando para despues inyectarlo por medio de props al componente hijo que seria este

Esta bien hacerlo pero no veo necesidad de ello 🤔, lo que si veo necesidad es de separarlo en un custom-hook que sea lo hagas en el hijo o en el padre lo tienes que hacer

Por que?

Por que hay muchos hooks, variables y propiedades dentro de ese custom-hook que te estoy comentando que realmente no le importan ni al padre ni al hijo, por eso conviene encapsularlos, en persona te podria explicar un poco mas de esta logica por que es fundamental no solo para custom-hooks si no para encapsulamiento en general de CUALQUIER COSA xP

2023-11-22 12:27 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +  }
Creo que me acabas de decir el por que hacerlo una funcion

La justificacion de por que hacer de eso una funcion esta clara xD, 100% deacuerdo

Solo digo que esta en un sitio equivocado, no deberia estar dentro del componente si no fuera del mismo (pero en el mismo archivo), en lla linea 93

2023-11-22 12:34 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +  const id = parseInt(useParams<RouteParams>().id!);
Una funcion extra xddd, osea un custom-hook, estas obsesionado con componentes extras (?

2023-11-22 12:37 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +      console.log(error);
Con el siguiente Sprint te refieres a este verdad xd?, para el anterior si es medio equisde, pero para ahorita si lo veo prioritario xP

2023-11-22 12:38 UTC, Hector1567XD commented on src/features/auth/Login.tsx
> +import useRedirectWhenLogged from "../../hooks/use-redirect-when-logged";
Claro po, pero ahora que lo agregaste hay que hacerlo xP

2023-11-22 12:46 UTC, Hector1567XD commented on src/features/profile/components/show-skills.tsx
> +        </Typography>
Dale!, dejalo para el siguiente sprint (este) xD

2023-11-22 12:50 UTC, Hector1567XD commented on src/features/profile/components/show-experiences.tsx
> +
Lo hablamos ne persona por que yo tampoco estoy seguro de que hacer en estos casos xd, pero es mas que nada para ahorrar espacio

2023-11-22 12:50 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +      {loggedUser && loggedUser.id == id && (
@luizzzito

2023-11-22 12:50 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +      <Link to="/dashboard"> Regresar </Link>
@luizzzito

2023-11-22 12:50 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +      <ShowSkills />
@luizzzito

2023-11-22 12:51 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +      <Typography variant="h6">{profile.description}</Typography>
@luizzzito

2023-11-22 12:54 UTC, Hector1567XD requested changes

2023-11-22 12:54 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +  const { profile, loggedUser, id } = useProfileState();
Te dije que encapsularas y esta bien, pero encapsulaste cosas que era diferentes entre si xD

Es decir, loggedUser deberia ser agnostico de useProfileState

El useProfileId si podria estar dentro de useProfileState pero la verdad yo propondria desacoplarlo

2023-11-22 14:21 UTC, luizzzito commented on src/features/profile/Profile.tsx
> +      <ShowSkills />
Listo hijo

2023-11-22 14:36 UTC, luizzzito commented on src/features/profile/Profile.tsx
> +  const { profile, loggedUser, id } = useProfileState();
no entiendo¿

2023-11-22 14:37 UTC, luizzzito commented on src/features/profile/components/show-skills.tsx
> +        </Typography>
XD

2023-12-07 18:17 UTC, closed without merging