Feature/new homepage: Nueva home page
EquestriaReapers/ER-frontend pull request #32
Opened 2024-01-06 14:25 UTC by Jesus-D-Rodriguez

HOme page nueva, el link esta en /landing de forma provisional

2024-01-06 16:32 UTC, luizzzito approved these changes
Hice cambios con acentos, nombres de archivos, y redirecciones de botones

2024-01-06 18:05 UTC, Hector1567XD requested changes
Falta publicar en staging y el tema de los profiles random

2024-01-07 11:56 UTC, Yisustxz approved these changes
una vaina bien

2024-01-11 01:45 UTC, Hector1567XD approved these changes

2024-01-12 01:01 UTC, merged