Epic/refactoring first mvp
EquestriaReapers/ER-frontend pull request #5
Opened 2023-11-23 19:32 UTC by luizzzito

🤔 Problem
El codigo era "stinky", por lo que habia que refactorizar.

✅ Solution
Encapsulamiento, aplicar las buenas practicas a los componentes (o eso intente) xd

2023-11-26 20:18 UTC, Hector1567XD requested changes

2023-11-26 20:18 UTC, Hector1567XD commented on src/core/profiles/types.ts
> +}
Esto ahora hay que ponerlo en ingles xD @HopeAero @luizzzito, ponganse deacuerdo en los nombres nuevos de cada campo

2023-11-26 20:18 UTC, Hector1567XD commented on src/features/auth/Login.tsx
> +import useRedirectWhenLogged from "../../hooks/use-redirect-when-logged";
Rutas absolutas
```suggestion
import useRedirectWhenLogged from "hooks/use-redirect-when-logged";
```

2023-11-26 20:25 UTC, Hector1567XD requested changes

2023-11-26 20:25 UTC, Hector1567XD commented on src/features/auth/Login.tsx
> +        console.log(error);
No se si esto sea de este PR de otro pero...
```suggestion
         showErrorToast(error)
```

2023-11-26 20:25 UTC, Hector1567XD commented on src/features/auth/Register.tsx
> +  useRedirectWhenRegistered();
Esto es un hook totalmente independiente de `useRegister` y no deberia estar dentro del mismo, le estarias dando demaciadas responsabilidades a `useRegister()` de caso contrario
```suggestion
```

2023-11-26 20:25 UTC, Hector1567XD commented on src/features/auth/Register.tsx
> +    ) => {
El tio bob lo dice, usa un objeto cuando son mas de 2 argumentos en una funcion
```suggestion
    async ({
      name,
      email,
      password,
      confirmPassword
    }: RegisterPayload) => {
```

2023-11-26 20:25 UTC, Hector1567XD commented on src/features/auth/Register.tsx
> +        if (!name || !email || !password || !confirmPassword) return;
Seria bueno que instales una libreria para hacer estas validaciones 🤔, lo veo como una necesidad super grande, pero supongo que sera para despues y por ahora seguiras asi

2023-11-26 20:25 UTC, Hector1567XD commented on src/features/auth/Register.tsx
> +        if (!name || !email || !password || !confirmPassword) return;
Alejandro usa una que le encanta que se llama `zod`, es https://www.npmjs.com/package/zod

La recomiendo, es muy buena

2023-11-26 20:25 UTC, Hector1567XD commented on src/features/auth/Register.tsx
> +        }
Si la contraseña difiere de la confirmacion de contraseña tiene que haber un mensaje de error especifico para ello

2023-11-26 20:32 UTC, Hector1567XD requested changes

2023-11-26 20:32 UTC, Hector1567XD commented on src/features/auth/Register.tsx
> +        console.log(error)
Maybe...
```suggestion
        showErrorToast(error);
```

2023-11-26 20:32 UTC, Hector1567XD commented on src/features/auth/register-form/RegisterForm.tsx
> +    const {name, email, password, confirmPassword, onChangeName, onChangeEmail, onChangePassword, onChangeConfirmPassword} = useRegisterFormState();
En estos casos son donde quiza si convenga usar la otra aproximacion 🤔 ... pero dejemoslo asi ✅

2023-11-26 20:32 UTC, Hector1567XD commented on src/features/auth/register-form/RegisterForm.tsx
> +                onSubmit(name, email, password, confirmPassword);
Mas de 2 argumentos, objeto
```suggestion
                onSubmit({ name, email, password, confirmPassword });    
```

2023-11-26 20:32 UTC, Hector1567XD commented on src/features/auth/register-form/RegisterForm.tsx
> +    onSubmit: (name: string, email: string, password: string, confirmPassword: string) => void;
```suggestion
    onSubmit: (objeto: TipoObjeto) => void;
```

2023-11-26 20:32 UTC, Hector1567XD commented on src/features/auth/register-form/RegisterForm.tsx
> +export interface props {
Cuidado con los estilos de nobramiento ⚠️!
```suggestion
export interface Props {
```

2023-11-26 20:32 UTC, Hector1567XD commented on src/features/auth/register-form/RegisterForm.tsx
> +const RegisterForm: FunctionComponent<props> = ({disabled, onSubmit}) =>{
Instala Prettier o Linter ⚠️!!! con urgencia xD

```suggestion
const RegisterForm: FunctionComponent<Props> = ({ disabled, onSubmit }) =>{
```

2023-11-26 20:34 UTC, Hector1567XD requested changes

2023-11-26 20:34 UTC, Hector1567XD commented on src/features/auth/register-form/use-register-form-state.ts
> +    }
Hmmm, no estoy seguro, pero quiza deberian ser callbacks? por el tema de usarlos dentro de un `useEffect`

```suggestion
    const onChangeName = useCallback((event: ChangeEvent<HTMLInputElement>) => {
        setName(event.target.value);
    }, []);

    const onChangeEmail = useCallback((event: ChangeEvent<HTMLInputElement>) => {
        setEmail(event.target.value);
    }, []);

    const onChangePassword = useCallback((event: ChangeEvent<HTMLInputElement>) => {
        setPassword(event.target.value);
    }, []);

    const onChangeConfirmPassword = useCallback((event: ChangeEvent<HTMLInputElement>) => {
        setConfirmPassword(event.target.value);
    }, []);
```

2023-11-26 20:34 UTC, Hector1567XD commented on src/features/auth/store/auth-slice.ts
> +      localStorage.setItem('auth', JSON.stringify(state))
👀 ...
```suggestion
```

2023-11-26 20:34 UTC, Hector1567XD commented on src/features/auth/store/auth-slice.ts
> +      localStorage.removeItem('auth');
👀 ...
```suggestion
```

2023-11-26 20:57 UTC, Hector1567XD commented on src/features/dashboard/Dashboard.tsx
> +  }
```suggestion
  if (!user) return null;
```

2023-11-26 20:57 UTC, Hector1567XD commented on src/features/dashboard/Dashboard.tsx
> +  };
Te recomiendo que siempre que pases una funcion como prop sea un `useCallback`
```suggestion
  const onLogout = useCallback(() => {
    dispatch(logout());
    navigate("/home");
  }, []);
```

2023-11-26 20:57 UTC, Hector1567XD commented on src/features/profile/Profile.tsx
> +  const profile = useProfile(id);
Esta bellaco esto ✅
```suggestion
  const id = parseInt(useParams<RouteParams>().id!);
  const profile = useProfile(id);
```
Aunque tambien se puede encapsular un poco mas el tema del parametro, lo haria en un custom-hook que crees en este mismo archivo
```suggestion
  const id = useParamProfileId();
  const profile = useProfile(id);
```

2023-11-26 20:57 UTC, Hector1567XD commented on src/features/profile/edit-profile/modal-content.tsx
> +  setIsOpen: (arg0: boolean) => void;
arg0 ??? ese nombre no es nada intuitivo :s 
```suggestion
  setIsOpen: (???: boolean) => void;
```

2023-11-26 20:57 UTC, Hector1567XD commented on src/features/profile/edit-profile/modal-content.tsx
> +export interface EditProfileModalContentProps {
Es de uso interno este prop, creo que basta con poner Props y ya
```suggestion
export interface Props {
```

2023-11-26 20:57 UTC, Hector1567XD commented on src/features/profile/edit-profile/modal-content.tsx
> +import useForm from "./use-form";
Por el contrario aqui si creo hay que ser mas especifico, form que? de que?, la ruta si da un poco de contexto pero al ser un archivo diria ayudaria ser mas especifico
```suggestion
import useEditProfileForm from "./use-edit-profile-form";
```

Ademas de que se diferencia esto de `useEditProfileFormState`????

Si `useEditProfileFormState` se encarga de recopilar la informacion es un buen nombre o incluso Form sin STate

Pero entiendo que se encarga de definir si esta abierto o no el formulario??? siendo asi podria tener un nombre como 
`useOpenForm({ setIsOpen, user });`

O si es que se encarga de "enviar" el formulario entonces creeria seria mas bien como
`useDispatchEditProfile({ setIsOpen, user });`

o algo asi como
`useOnSubmitForm({ setIsOpen, user });`

2023-11-26 20:57 UTC, Hector1567XD commented on src/legacy/services/profile.service.ts
> +   //
debe hacer throw del error ya sea del que te manda el backend o de uno personalizado xd, esto nunca fallara si el backend llega a dar error entonces habran errores silenciosos
```suggestion
   throw new BackendError(error);
```

2023-11-26 20:57 UTC, Hector1567XD commented on src/legacy/services/profile.service.ts
> +    //
```suggestion
    throw new BackendError(error);
```

2023-11-26 20:57 UTC, Hector1567XD commented on src/legacy/services/users.service.ts
> +        //
```suggestion
        throw new BackendError(error);
```

2023-11-26 20:57 UTC, Hector1567XD commented on src/legacy/profile/EditProfileForm.tsx
>      }
xd?

2023-11-26 21:20 UTC, Hector1567XD requested changes

2023-11-26 21:20 UTC, Hector1567XD commented on src/hooks/use-redirect-when-unlogged.ts
> +    }
```suggestion
    if (!isLogged) navigate(`/login`);
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/hooks/use-redirect-when-logged.ts
> +      navigate(`/dashboard`);
Esto habria que hacerlo despues, no ahorita, pero yo creo que por defecto el redirect when logged seria a este lugar:
```suggestion
      navigate(`/profile/${....}`);
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/delete-skills/use-delete-skill.tsx
> +      console.log(error);
La toast hace falta
```suggestion
      showErrorToast(error);
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/delete-skills/use-delete-skill.tsx
> +  setIsOpen: (arg0: boolean) => void;
Nombre de argimemto poco intuitivo
```suggestion
  setIsOpen: (xxx: boolean) => void;
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/delete-skills/modal.tsx
> +        aria-describedby="It is used to delete skills"
Esto no deberia estar en español?
```suggestion
        aria-labelledby=""
        aria-describedby=""
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/show-skills/skill-card.tsx
> +
wuen componente <3 ♥

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/show-skills/skill-card.tsx
> +
```suggestion
const SkillCard: FunctionalComponent<Props> = ({ item }) => {
  return (
    <div>
      <Typography variant="h6">{item.name}</Typography>
    </div>
  );
};

interface Props {
   item: Skill;
}

```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/delete-skills/modal-content.tsx
> +      <Typography>¿Estás seguro de que quieres borrar la habilidad?</Typography>
Grandeeeeeee ventana de confirmacion ❤

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/delete-skills/modal-content.tsx
> +      <Button onClick={() => setIsOpen(false)}>Regresar</Button>
Yo haria que se inyectara como prop directamente el closeModal mas que el setIsOpen
```suggestion
      <Button onClick={closeModal}>Regresar</Button>
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/add-skills/use-form.tsx
> +  };
Esto definitivamente debe ser un useCallback, recuerda tambien, cuando pasa una funcion como parametro de un componente por props debe ser si o si un useCallback

```suggestion
  const onSubmitForm = useCallback(async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    try {
      if (!token || !selectedSkillId) return;
      const skillId = parseInt(selectedSkillId);
      const data = await addProfileSkill(token, { skillId });
      setIsOpen(false);
      return data;
    } catch (error) {
      console.log(error);
    }
  }, [...]);
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/show-skills/show-skills.tsx
> +interface ShowSkillsProps {
uso local, nombres locales
```suggestion
interface Props {
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/show-skills/show-skills.tsx
> +const ShowSkills = ({ skills, isEditable }: ShowSkillsProps) => {
```suggestion
const ShowSkills = ({ skills, isEditable }: Props) => {
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/add-skills/use-all-skills.tsx
> +};
Por que obtendrias TODOS los skills o-0????

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/add-skills/use-all-skills.tsx
> +  return { allSkills };
Cuando se devuelve una sola funcion o propiedad puedes no enviar un objeto si no enviarla directa asi de una
```suggestion
  return allSkills;
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/add-skills/modal.tsx
> +        aria-describedby="se usa para agregar habilidades"
Maybe
```suggestion
        aria-labelledby="Agregar habilidades"
        aria-describedby="Se usa para agregar habilidades"
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/use-profile.ts
> +      console.log(error);
```suggestion
      //  mensaje de error ?
 ```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/skills/add-skills/form-content.tsx
> +  const { allSkills } = useAllSkills(token!);
Creeria puedes dejar el hook de obtencion del token dentro, me parece mas responsabilidad de ese mismo hook mas que del componente en si
```suggestion
  const allSkills = useAllSkills();
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/services/profile.service.ts
> +
separar en distintos archivos xd

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/profile-content/profile-skills.tsx
> +export interface ProfileSkillProps {
```suggestion
const ProfileSkills = ({
  isEditable,
  currentProfileSkills,
}: Props) => {
  return (
    <>
      <Typography variant="h4">Habilidades:</Typography>
      {isEditable && <AddSkillsModal />}
      <ShowSkills skills={currentProfileSkills} isEditable={isEditable}/>
    </>
  );
};

export interface Props {
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/profile-content/profile-experience.tsx
> +}
```suggestion
const ProfileExperience = ({
  isEditable,
  currentProfileExperience,
}: Props) => {
  return (
    <div>
      <Typography variant="h4">Experiencia:</Typography>
      {isEditable && <EditProfileModal />}
      <ShowExperiences experience={currentProfileExperience} />
    </div>
  );
};

export interface Props {
  isEditable: boolean;
  currentProfileExperience: Experience[];
}
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/profile-content/profile-content.tsx
> +export interface ProfileContentProps {
```suggestion
export interface Props {
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/edit-profile/use-form.tsx
> +      console.log(error);
```suggestion
  // El toast o mensaje de erorr
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/edit-profile/use-form.tsx
> +  const onSubmitForm = async (event: FormEvent<HTMLFormElement>) => {
```suggestion
  const onSubmitForm = useCallback(async (event: FormEvent<HTMLFormElement>) => {
```

2023-11-26 21:20 UTC, Hector1567XD commented on src/features/profile/edit-profile/use-edit-profile-form-state.ts
> +  }, [getUserInfo]);
Encapsulalo en un custom-hook que estara dentro de este custom-hook, aunque la verdad estoy un poco dudoso en si meterlo dentro, la verdad lo veo como una responsabilidad distinta, podria ser un custom-hook nuevo pero que este AFUERA de este

```suggestion
  useGetUserProfileInfo({ setName, setDescription });
```

2023-11-26 21:23 UTC, Hector1567XD requested changes

2023-11-26 21:23 UTC, Hector1567XD commented on src/features/profile/skills/add-skills/use-all-skills.tsx
> +const useAllSkills = (token: string) => {
Este hook me parece demaciado calavera :S, se supone debe ser un autocompletado, a no ser que esto sea algo TEMPORAL

De momento para mi esto es lo mas ⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️

2023-12-10 02:59 UTC, luizzzito commented on src/core/profiles/types.ts
> +}
listo

2023-12-10 03:00 UTC, luizzzito commented on src/features/profile/skills/add-skills/use-all-skills.tsx
> +const useAllSkills = (token: string) => {
si, es que eso va a cambiar y sera un autocompletado, por lo que se quedara ahi MIENTRAS TANTO

2023-12-10 03:02 UTC, luizzzito commented on src/features/auth/Login.tsx
> +        console.log(error);
no le corresponde a este PR

2023-12-10 03:04 UTC, luizzzito commented on src/features/auth/Register.tsx
> +  useRedirectWhenRegistered();
Valem creo que ademas esto no deberia ser un hook, igual y solo deberia ser el navigate. DE TODAS FORMAS, creo que eso lo podriamos ver en el PR de JEsus david

2023-12-21 12:31 UTC, Hector1567XD approved these changes
Hay mucho que mejorar pero que ya se esta haciendo en las tareas de la epica de "GESTIONAR PERFIL"

2023-12-21 12:31 UTC, Hector1567XD commented on src/features/auth/use-redirect-when-registered.ts
> +export default function useRedirectWhenRegistered() {
xd
```suggestion
export default function useRedirectWhenLogged() {
```

2023-12-21 12:31 UTC, Hector1567XD commented on src/features/auth/use-redirect-when-registered.ts
> +export default function useRedirectWhenRegistered() {
Pero supongo ya se esta atajando en otro PR

2023-12-21 12:31 UTC, Hector1567XD commented on src/hooks/use-redirect-when-logged.ts
> +export default function useRedirectWhenLogged() {
No es lo mismo que redirectWhenRegistetered?

2023-12-21 15:09 UTC, Yisustxz approved these changes
la verdadera vaina bien

2023-12-23 01:38 UTC, Nannajpg approved these changes

2023-12-23 22:35 UTC, merged